"""Evidence-Governed Variation slice."""

from .arms import ARM_IDS, ArmIsolation, ArmPolicy, ArmWorkspace, arm_policy
from .adapter import (
    ADAPTER_MANIFEST_NAME,
    ADAPTER_MANIFEST_SCHEMA,
    SealedAdapterArtifact,
    SealedAdapterManifest,
    build_local_adapter_manifest,
)
from .checkpoint import CHECKPOINT_SCHEMA, CheckpointStore, VariationCheckpoint
from .errors import (
    VariationBudgetError,
    VariationCheckpointError,
    VariationConfigurationError,
    VariationDependencyError,
    VariationError,
    VariationIsolationError,
)
from .generator import CandidateContext, CandidateGenerator, CandidateProposal, DeterministicFixtureGenerator, ModelCandidateGenerator
from .loop import (
    AttemptRecord,
    BoundedCandidateLoop,
    CANDIDATE_SOURCE_LIMIT,
    ControllerEvaluationGateway,
    MAX_CANDIDATE_ATTEMPTS,
    VARIATION_PROTOCOL_DIGEST,
    VARIATION_PROTOCOL_SCHEMA,
    VariationReport,
    VariationRunner,
    VariationTask,
)
from .model import (
    ADAPTER_ATTESTATION_SCHEMA,
    AdapterApplicationAttestation,
    LoadedPinnedModel,
    MODEL_ARCHITECTURE,
    MODEL_CONFIG_CLASS,
    MODEL_MANIFEST_SCHEMA,
    MODEL_REPOSITORY,
    MODEL_REVISION,
    PinnedModelLoader,
    PinnedModelManifest,
    build_local_manifest,
    model_state_digest,
)
from .retrieval import (
    CorrectionAwareRetrieval,
    EvidenceRetrievalPolicy,
    OrdinaryFailureRetrieval,
    RETRIEVAL_POLICIES,
    RetrievedEvidence,
    RetrievalResult,
    SuccessOnlyRetrieval,
    retrieval_policy,
)
from .smoke import run_variation_smoke, scan_public_variation_report
from .remote import (
    REMOTE_VARIATION_REQUEST_SCHEMA,
    REMOTE_VARIATION_RESPONSE_SCHEMA,
    REMOTE_VARIATION_SERVICE_SCHEMA,
    RemoteControllerEvaluationGateway,
    RemoteEvaluatorServiceManifest,
    build_remote_evaluator_service_manifest,
    run_remote_evaluator_once,
)
from .private import PRIVATE_TRAJECTORY_SCHEMA, PrivateTrajectoryStore


__all__ = [
    "ARM_IDS",
    "ADAPTER_MANIFEST_NAME",
    "ADAPTER_MANIFEST_SCHEMA",
    "ADAPTER_ATTESTATION_SCHEMA",
    "AdapterApplicationAttestation",
    "AttemptRecord",
    "ArmIsolation",
    "ArmPolicy",
    "ArmWorkspace",
    "BoundedCandidateLoop",
    "CANDIDATE_SOURCE_LIMIT",
    "CHECKPOINT_SCHEMA",
    "CandidateContext",
    "CandidateGenerator",
    "CandidateProposal",
    "CheckpointStore",
    "ControllerEvaluationGateway",
    "CorrectionAwareRetrieval",
    "DeterministicFixtureGenerator",
    "EvidenceRetrievalPolicy",
    "LoadedPinnedModel",
    "MAX_CANDIDATE_ATTEMPTS",
    "MODEL_ARCHITECTURE",
    "MODEL_CONFIG_CLASS",
    "MODEL_MANIFEST_SCHEMA",
    "MODEL_REPOSITORY",
    "MODEL_REVISION",
    "ModelCandidateGenerator",
    "OrdinaryFailureRetrieval",
    "PinnedModelLoader",
    "PinnedModelManifest",
    "PRIVATE_TRAJECTORY_SCHEMA",
    "PrivateTrajectoryStore",
    "RETRIEVAL_POLICIES",
    "REMOTE_VARIATION_REQUEST_SCHEMA",
    "REMOTE_VARIATION_RESPONSE_SCHEMA",
    "REMOTE_VARIATION_SERVICE_SCHEMA",
    "RemoteControllerEvaluationGateway",
    "RemoteEvaluatorServiceManifest",
    "RetrievedEvidence",
    "RetrievalResult",
    "SealedAdapterArtifact",
    "SealedAdapterManifest",
    "SuccessOnlyRetrieval",
    "VARIATION_PROTOCOL_DIGEST",
    "VARIATION_PROTOCOL_SCHEMA",
    "VariationBudgetError",
    "VariationCheckpoint",
    "VariationCheckpointError",
    "VariationConfigurationError",
    "VariationDependencyError",
    "VariationError",
    "VariationIsolationError",
    "VariationReport",
    "VariationRunner",
    "VariationTask",
    "arm_policy",
    "build_local_manifest",
    "build_local_adapter_manifest",
    "build_remote_evaluator_service_manifest",
    "model_state_digest",
    "retrieval_policy",
    "run_variation_smoke",
    "run_remote_evaluator_once",
    "scan_public_variation_report",
]
